### ISSUE TITLE
Add Dart Language for the !role command

### ISSUE THREAD

**Issue by DeepRobin** [Biospheere/c0debaseBot#103]
[https://www.dartlang.org/](https://www.dartlang.org/)

**Comment by Chromecube** [comment]
Please have a look at the [role command](https://github.com/Biospheere/c0debaseBot/blob/master/src/main/java/de/c0debase/bot/commands/general/RoleCommand.java#L40). The bot has nothing to do with which roles are available, this is managed by the guild administration in the server settings.

Creating this issue here probably won't help you, maybe talk to an administrator.
